# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js LTS on Alpine
FROM node:lts-alpine AS builder

# Install build dependencies for sharp
RUN apk add --no-cache python3 make g++ 

WORKDIR /app

# Copy package manifests and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Install project dependencies (including dev for build)
RUN npm ci --ignore-scripts

# Install TypeScript compiler
RUN npm install typescript --no-save

# Copy source files
COPY src ./src

# Build TypeScript
RUN npm run build

# Production image
FROM node:lts-alpine

WORKDIR /app

# Install runtime dependencies
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Copy built artifacts
COPY --from=builder /app/dist ./dist

# If you want to mount or include images at runtime, you can adjust IMAGE_ROOT volume
ENV IMAGE_ROOT=/images

# Expose no ports (stdio transport)
ENTRYPOINT ["node", "dist/image-resolver.js"]
